import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import { useState } from 'react'
import InfiniteScroll from "react-infinite-scroll-component";
import Link from 'next/link';

const defaultEndpoint = 'http://localhost:8000/phones'
export async function getServerSideProps() {
  const res = await fetch(defaultEndpoint)
  const data = await res.json()
  return {
    props: {
      data
    }
  }
}
export default function Home({ data }) {
  const { results: defaultResults = [] } = data
  const [results, updateResults] = useState(defaultResults)
  const [next, updateNext] = useState(data.next)
  const [hasMore, setHasMore] = useState(true)

  const getMorePhones = async () => {
    const res = await fetch(next)
    const newPhones = await res.json()
    updateResults([...results, ...newPhones.results])
    if (newPhones == null) {
      setHasMore(false)
    }
    updateNext(newPhones.next)
  }
  return (
    <>
      <div className={styles.container}>
        <Head>
          <title>Phone Models</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>

        <main className={styles.main}>
          <h1 className={styles.title}>
            Phone Models
          </h1>

          <p className={styles.description}>
            {data.count} phone models!
          </p>
          <InfiniteScroll
            dataLength={results.length}
            next={getMorePhones}
            hasMore={hasMore}
            loader={<h3>Loading...</h3>}
            endMessage={<h4>nomore data</h4>}>
            <ul className={`grid grid-cols-2 gap-y-8`}>
              {results.map(result => {
                const { id, brand_name, model_name, url, image_url } = result
                return (
                  <li key={id} className={` ${styles.card} w-full h-full`}>
                    <Link href={`/phone/${id}`}>
                    <a className='w-full h-full  flex flex-col items-center justify-center text-center'>
                      <img loading='lazy' src={image_url} alt={model_name}></img>
                      <h2>{brand_name} {model_name}</h2>
                    </a>
                    </Link>
                  </li>
                )
              })}

            </ul>
          </InfiniteScroll>

        </main>

        <footer className={styles.footer}>
          <a
            href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
            target="_blank"
            rel="noopener noreferrer"
          >
            Powered by{' '}
            <span className={styles.logo}>
              <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
            </span>
          </a>
        </footer>
      </div>
    </>
  )
}
