import Head from 'next/head'
import Link from 'next/link';

const defaultEndpoint = 'http://localhost:8000/phones/'
export async function getServerSideProps(context) {
    const res = await fetch(defaultEndpoint + context.params.id)
    const data = await res.json()
    console.log(data)
    return {
        props: {
            data
        }
    }
}
export default function Home({ data }) {
    const { image_url, brand_name, model_name, os, popularity, lowest_price, highest_price, best_price, sellers_amount, screen_size, memory_size,
        battery_size, release_date } = data
    return (
        <>
            <div className='w-[100vw] h-[100vh]'>
                <Head>
                    <title>Phone Models</title>
                    <meta name="description" content="Generated by create next app" />
                    <link rel="icon" href="/favicon.ico" />
                </Head>

                <main className='w-full h-full flex flex-col justify-center items-center'>
                    <div className='h-[50%] w-[50%] flex justify-center items-center'>
                        <img loading='lazy' src={image_url} alt={data['model_name']}></img>
                        <div>
                            <h1>{brand_name} {model_name}</h1>
                            <p>os: {os}</p>
                            <p>popularity: {popularity}</p>
                            <p>price: {lowest_price}-{highest_price} ({best_price})</p>
                            <p>sellers_amount: {sellers_amount}</p>
                            <p>screen_size: {screen_size}</p>
                            <p>memory_size: {memory_size}</p>
                            <p>battery_size: {battery_size}</p>
                            <p>release_date: {release_date}</p>
                        </div>
                    </div>
                    <Link href='/'>
                        <a>Back</a>
                    </Link>
                </main>
            </div>
        </>
    )
}
